disabled = false
languageCode = "vi"
languageName = "Vietnamese"
weight = 3
title = "Ghi chú của JYu"

[params]
displayName = "Tiếng Việt"
isoCode = "vi"
rtl = false
dateFormat = "2 January 2006"

[params.author]
name = "結語JYu"
image = "img/author.png"
headline = "Tiếp tục phát triển, theo đuổi sự bình yên"
bio = "Xin chào, tôi là JYu"
links = [
  { x-twitter = "https://x.com/IamJYu" },
  { threads = "https://www.threads.com/@backend.cat" },
  { medium = "https://medium.com/@jyu1999" },
  { linkedin = "https://www.linkedin.com/in/chieh-yu-chan-123814190/" },
]

