disabled = false
languageCode = "ja"
languageName = "Japanese"
weight = 4
title = "JYuのノート"

[params]
displayName = "日本語"
isoCode = "ja"
rtl = false
dateFormat = "2006年1月2日"

[params.author]
name = "結語JYu"
image = "img/author.png"
headline = "成長を続け、平穏を追求する"
bio = "こんにちは、JYuです"
links = [
  { x-twitter = "https://x.com/IamJYu" },
  { threads = "https://www.threads.com/@backend.cat" },
  { medium = "https://medium.com/@jyu1999" },
  { linkedin = "https://www.linkedin.com/in/chieh-yu-chan-123814190/" },
]

